eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    gateway:
      # cores 처리
      # 각 service module은 web browser와 직접 통신하지 않으므로 단일진입점인 gateway 담당
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - 'http://localhost:3000'
            allowedMethods: '*'
            allowedHeaders: '*'
            exposedHeaders: '*'
            allowCredentials: true
      # Eureka Server에 등록된 client를 찾아서 사용자의 url_pattern을 매핑하는 작업
      routes:
        # User
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            # 첫번째 접두어를 제거
            # Browser : http://server.mhpark0605.shop/user-service/users/signIn
            # Inner   : http://server.mhpark0605.shop/users/signIn
            - StripPrefix=1
          uri: lb://user-service

        # STORY
        - id: story-service
          predicates:
            - Path=/story-service/**
          filters:
            - StripPrefix=1
          uri: lb://story-service

        # Learning
        - id: learning-service
          predicates:
            - Path=/learning-service/**
          filters:
            - StripPrefix=1
          uri: lb://learning-service

        # Gamification
        - id: gamification-service
          predicates:
            - Path=/gamification-service/**
          filters:
            - StripPrefix=1
          uri: lb://gamification-service
        
        # Analytics
        - id: analytics-service
          predicates:
            - Path=/analytics-service/**
          filters:
            - StripPrefix=1
          uri: lb://analytics-service
        
        # Recommendation
        - id: recommendation-service
          predicates:
            - Path=/recommendation-service/**
          filters:
            - StripPrefix=1
          uri: lb://recommendation-service


jwt:
  secret: aitale-super-secret-key-for-miniproj-123456789

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: story-service
        url: /story-service/v3/api-docs
      - name: learning-service
        url: /learning-service/v3/api-docs
      - name: gamification-service
        url: /gamification-service/v3/api-docs
      - name: analytics-service
        url: /analytics-service/v3/api-docs
      - name: recommendation-service
        url: /recommendation-service/v3/api-docs