cloud:
  bus:
    enabled: true

eureka:
  client:
    enabled: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/inspire?useSSL=false&requireSSL=false  
    username: ${DB_ADMIN:root}  
    password: ${DB_PASSWORD:password}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate: 
        ddl-auto: create
    show-sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 6000ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  