server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092

springfox:
  documentation:
    swagger-ui:
      enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

ai:
  service:
    url: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh
